/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author CherryCe
 */
public class GUI_frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form GUI_frmLogin
     */
    public GUI_frm_Login() {
        initComponents();
        setLocationRelativeTo(null);
        pnlDangNhap();

    }

    public void pnlDangNhap() {
        pnlLogin.removeAll();
        pnlLogin.add(new GUI_pnl_DangNhap());

        lblDangNhap.setForeground(new Color(255, 255, 255));
        pnlLogin.validate();
    }

    public void pnlQuenMatKhau() {
        pnlLogin.removeAll();
        lblDangNhap.setForeground(new Color(0, 0, 0));
        pnlLogin.add(new GUI_pnl_QuenMatKhau());
        lblQuenMatKhau.setForeground(new Color(255, 255, 255));
        pnlLogin.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        pnlChucNang = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblQuenMatKhau = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(550, 450));

        pnlLogin.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));
        pnlLogin.setMinimumSize(new java.awt.Dimension(400, 450));
        pnlLogin.setLayout(new java.awt.CardLayout());

        pnlChucNang.setBackground(new java.awt.Color(255, 255, 255));
        pnlChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setBackground(new java.awt.Color(255, 255, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hotel (2).png"))); // NOI18N
        lblLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlChucNang.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

        lblQuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        lblQuenMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset-password (2).png"))); // NOI18N
        lblQuenMatKhau.setText("Quên Mật Khẩu");
        lblQuenMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblQuenMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
        });
        pnlChucNang.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 150));

        lblDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        lblDangNhap.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(62, 73, 95));
        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/enter.png"))); // NOI18N
        lblDangNhap.setText("Đăng Nhập");
        lblDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });
        pnlChucNang.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        // TODO add your handling code here:
        pnlDangNhap();
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        // TODO add your handling code here:
        pnlQuenMatKhau();
    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JPanel pnlChucNang;
    private javax.swing.JPanel pnlLogin;
    // End of variables declaration//GEN-END:variables
}
