/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.MouseEvent;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChiTietDichVu extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlChiTietPhong
     */
    public GUI_pnl_ChiTietDichVu() {
        initComponents();
        lblPhongSo.setText("" + GUI_pnl_ThuNgan.index);
    }

    public void text(int i) {

    }

    public void showPopUp(MouseEvent evt) {
        jPopupMenu1.show(this, evt.getX(), evt.getY());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        sdoChiTietDichVu = new HELPER.PanelShadow();
        lblSetPhongSo = new javax.swing.JLabel();
        lblSetNgay = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblMaHoaDon = new javax.swing.JLabel();
        scrDichVu = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        lblSetMaHoaDon = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblPhongSo = new javax.swing.JLabel();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem2);

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(350, 210));
        setPreferredSize(new java.awt.Dimension(350, 210));

        sdoChiTietDichVu.setBackground(new java.awt.Color(255, 255, 255));
        sdoChiTietDichVu.setMinimumSize(new java.awt.Dimension(350, 210));
        sdoChiTietDichVu.setPreferredSize(new java.awt.Dimension(350, 210));
        sdoChiTietDichVu.setShadowOpacity(0.3F);
        sdoChiTietDichVu.setShadowSize(4);
        sdoChiTietDichVu.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        sdoChiTietDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdoChiTietDichVuMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sdoChiTietDichVuMouseReleased(evt);
            }
        });
        sdoChiTietDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetPhongSo.setBackground(new java.awt.Color(255, 255, 255));
        lblSetPhongSo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetPhongSo.setForeground(new java.awt.Color(62, 73, 95));
        lblSetPhongSo.setText("302");
        sdoChiTietDichVu.add(lblSetPhongSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 30, 20));

        lblSetNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetNgay.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgay.setText("22/09/22");
        sdoChiTietDichVu.add(lblSetNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 70, 20));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(97, 177, 90));
        lblTongTien.setText("2250,000");
        sdoChiTietDichVu.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 40));

        lblMaHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblMaHoaDon.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaHoaDon.setForeground(new java.awt.Color(153, 153, 153));
        lblMaHoaDon.setText("Mã Hóa Đơn");
        sdoChiTietDichVu.add(lblMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        scrDichVu.setBackground(new java.awt.Color(255, 255, 255));

        tblDichVu.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrDichVu.setViewportView(tblDichVu);

        sdoChiTietDichVu.add(scrDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 110));

        lblSetMaHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaHoaDon.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetMaHoaDon.setForeground(new java.awt.Color(62, 73, 95));
        lblSetMaHoaDon.setText("220923001");
        sdoChiTietDichVu.add(lblSetMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 20));

        lblNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblNgay.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblNgay.setText("Ngày");
        sdoChiTietDichVu.add(lblNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 30, 20));

        lblPhongSo.setBackground(new java.awt.Color(255, 255, 255));
        lblPhongSo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblPhongSo.setForeground(new java.awt.Color(153, 153, 153));
        lblPhongSo.setText("Phòng Số");
        sdoChiTietDichVu.add(lblPhongSo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sdoChiTietDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietDichVuMouseClicked
        // TODO add your handling code here:
        scrDichVu.setVisible(false);
        sdoChiTietDichVu.setSize(350, 110);
    }//GEN-LAST:event_sdoChiTietDichVuMouseClicked

    private void sdoChiTietDichVuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietDichVuMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sdoChiTietDichVuMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    public javax.swing.JLabel lblMaHoaDon;
    public javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblPhongSo;
    public javax.swing.JLabel lblSetMaHoaDon;
    public javax.swing.JLabel lblSetNgay;
    public javax.swing.JLabel lblSetPhongSo;
    public javax.swing.JLabel lblTongTien;
    private javax.swing.JScrollPane scrDichVu;
    public HELPER.PanelShadow sdoChiTietDichVu;
    private javax.swing.JTable tblDichVu;
    // End of variables declaration//GEN-END:variables
}
