/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_DangNhap extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlDangNhap
     */
    public GUI_pnl_DangNhap() {
        initComponents();
    }

    public void loading() {
        GUI_dal_Loading loading = new GUI_dal_Loading(null, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatKhau = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        cboLuuDangNhap = new javax.swing.JCheckBox();
        lblWebsite = new javax.swing.JLabel();
        lblSetHoTro = new javax.swing.JLabel();
        lblSetWebsite = new javax.swing.JLabel();
        lblHoTro = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        lblDangNhap = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));

        lblMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/padlock.png"))); // NOI18N

        txtTenDangNhap.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(62, 73, 95));
        txtTenDangNhap.setText("admin");
        txtTenDangNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenDangNhap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenDangNhapFocusLost(evt);
            }
        });
        txtTenDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenDangNhapMouseClicked(evt);
            }
        });
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });

        cboLuuDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        cboLuuDangNhap.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cboLuuDangNhap.setForeground(new java.awt.Color(62, 73, 95));
        cboLuuDangNhap.setText("Lưu Đăng Nhập");

        lblWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(153, 153, 153));
        lblWebsite.setText("Website:");

        lblSetHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblSetHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetHoTro.setForeground(new java.awt.Color(62, 73, 95));
        lblSetHoTro.setText("Game2K");

        lblSetWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblSetWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetWebsite.setForeground(new java.awt.Color(62, 73, 95));
        lblSetWebsite.setText("MrPii.2k3");

        lblHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHoTro.setForeground(new java.awt.Color(153, 153, 153));
        lblHoTro.setText("Hỗ Trợ:");

        txtMatKhau.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        txtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        lblDangNhap.setBackground(new java.awt.Color(62, 73, 95));
        lblDangNhap.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setText("ĐĂNG NHẬP");
        lblDangNhap.setOpaque(true);
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });

        lblTenDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        lblTenDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profile-user.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(cboLuuDangNhap))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHoTro)
                .addGap(11, 11, 11)
                .addComponent(lblSetHoTro)
                .addGap(128, 128, 128)
                .addComponent(lblWebsite)
                .addGap(13, 13, 13)
                .addComponent(lblSetWebsite))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lblDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cboLuuDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void txtTenDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenDangNhapMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapMouseClicked

    private void txtTenDangNhapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusGained
        // TODO add your handling code here:
        if (txtTenDangNhap.getText().equals("admin")) {
            txtTenDangNhap.setText("");
        }
    }//GEN-LAST:event_txtTenDangNhapFocusGained

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        // TODO add your handling code here:
        new GUI_dal_Loading(null, true).setVisible(true);
        this.setVisible(false);
        new GUI_frm_Menu().setVisible(true);
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void txtTenDangNhapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenDangNhapFocusLost
        // TODO add your handling code here:
        if (txtTenDangNhap.getText().isEmpty()) {
            txtTenDangNhap.setText("admin");
        }
    }//GEN-LAST:event_txtTenDangNhapFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cboLuuDangNhap;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblHoTro;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblSetHoTro;
    private javax.swing.JLabel lblSetWebsite;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
