/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_QuenMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlDangKi
     */
    public GUI_pnl_QuenMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuenMatKhau = new javax.swing.JPanel();
        lblTenDangNhap = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblSetHoTro = new javax.swing.JLabel();
        lblSetWebsite = new javax.swing.JLabel();
        lblHoTro = new javax.swing.JLabel();
        lblDangKi = new javax.swing.JLabel();
        cboBaoMat = new javax.swing.JComboBox<>();
        txtBaoMat = new javax.swing.JTextField();
        lblBaoMat = new javax.swing.JLabel();
        pswMatKhau = new javax.swing.JPasswordField();
        txtTenDangNhap = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));

        pnlQuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuenMatKhau.setMinimumSize(new java.awt.Dimension(400, 450));
        pnlQuenMatKhau.setPreferredSize(new java.awt.Dimension(400, 450));

        lblTenDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        lblTenDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profile-user.png"))); // NOI18N

        lblWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(153, 153, 153));
        lblWebsite.setText("Website:");

        lblSetHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblSetHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetHoTro.setForeground(new java.awt.Color(62, 73, 95));
        lblSetHoTro.setText("Game2K");

        lblSetWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblSetWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetWebsite.setForeground(new java.awt.Color(62, 73, 95));
        lblSetWebsite.setText("MrPii.2k3");

        lblHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHoTro.setForeground(new java.awt.Color(153, 153, 153));
        lblHoTro.setText("Hỗ Trợ:");

        lblDangKi.setBackground(new java.awt.Color(62, 73, 95));
        lblDangKi.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblDangKi.setForeground(new java.awt.Color(255, 255, 255));
        lblDangKi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangKi.setText("ĐĂNG KÍ");
        lblDangKi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangKi.setOpaque(true);

        cboBaoMat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboBaoMat.setForeground(new java.awt.Color(62, 73, 95));
        cboBaoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboBaoMat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtBaoMat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtBaoMat.setForeground(new java.awt.Color(62, 73, 95));
        txtBaoMat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtBaoMat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBaoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaoMatActionPerformed(evt);
            }
        });

        lblBaoMat.setBackground(new java.awt.Color(255, 255, 255));
        lblBaoMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaoMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconfinder-securityprotectlockshield04-4021479_113137.png"))); // NOI18N

        pswMatKhau.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        pswMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        pswMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pswMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pswMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswMatKhauActionPerformed(evt);
            }
        });

        txtTenDangNhap.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(62, 73, 95));
        txtTenDangNhap.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });

        lblMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/padlock.png"))); // NOI18N

        javax.swing.GroupLayout pnlQuenMatKhauLayout = new javax.swing.GroupLayout(pnlQuenMatKhau);
        pnlQuenMatKhau.setLayout(pnlQuenMatKhauLayout);
        pnlQuenMatKhauLayout.setHorizontalGroup(
            pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pswMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblBaoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(cboBaoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtBaoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lblDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblSetHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(lblWebsite)
                .addGap(13, 13, 13)
                .addComponent(lblSetWebsite))
        );
        pnlQuenMatKhauLayout.setVerticalGroup(
            pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuenMatKhauLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBaoMat)
                    .addComponent(cboBaoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlQuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBaoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaoMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaoMatActionPerformed

    private void pswMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswMatKhauActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboBaoMat;
    private javax.swing.JLabel lblBaoMat;
    private javax.swing.JLabel lblDangKi;
    private javax.swing.JLabel lblHoTro;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblSetHoTro;
    private javax.swing.JLabel lblSetWebsite;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JPanel pnlQuenMatKhau;
    private javax.swing.JPasswordField pswMatKhau;
    private javax.swing.JTextField txtBaoMat;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
