/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_ThongTinGiaoCa extends javax.swing.JDialog {

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_ThongTinGiaoCa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoGiaoCa = new HELPER.PanelShadow();
        txtBanGiao = new javax.swing.JTextField();
        lblSetCongSuatPhong = new javax.swing.JLabel();
        lblDatCoc = new javax.swing.JLabel();
        lblTongChi = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblCaTruoc = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        spt_2 = new javax.swing.JSeparator();
        spt_1 = new javax.swing.JSeparator();
        lblTienPhatSinh = new javax.swing.JLabel();
        lblDaThu = new javax.swing.JLabel();
        lblTongCong = new javax.swing.JLabel();
        lblCongSuatPhong = new javax.swing.JLabel();
        lblCaTruc = new javax.swing.JLabel();
        lblCoKhach = new javax.swing.JLabel();
        lblThongTinGiaoCa = new javax.swing.JLabel();
        lblSetNgay = new javax.swing.JLabel();
        lblSetCaTruc = new javax.swing.JLabel();
        lblThongKePhong = new javax.swing.JLabel();
        lblBanGiao = new javax.swing.JLabel();
        lblDatTruoc = new javax.swing.JLabel();
        lblTraPhong = new javax.swing.JLabel();
        lblSetDaThu = new javax.swing.JLabel();
        lblSetTongCong = new javax.swing.JLabel();
        lblSetHoaDon = new javax.swing.JLabel();
        lblSetCaTruoc = new javax.swing.JLabel();
        lblSetTongChi = new javax.swing.JLabel();
        lblSetDatCoc = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        sdoChucNang = new HELPER.PanelShadow();
        lblThoat = new javax.swing.JLabel();
        lblGiaoCa = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(680, 470));
        setUndecorated(true);

        sdoGiaoCa.setBackground(new java.awt.Color(255, 255, 255));
        sdoGiaoCa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(33, 150, 243)));
        sdoGiaoCa.setMinimumSize(new java.awt.Dimension(680, 490));
        sdoGiaoCa.setPreferredSize(new java.awt.Dimension(680, 490));
        sdoGiaoCa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBanGiao.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtBanGiao.setForeground(new java.awt.Color(97, 177, 90));
        txtBanGiao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(97, 177, 90)));
        txtBanGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanGiaoActionPerformed(evt);
            }
        });
        sdoGiaoCa.add(txtBanGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 80, 30));

        lblSetCongSuatPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetCongSuatPhong.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetCongSuatPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblSetCongSuatPhong.setText("12.5%");
        sdoGiaoCa.add(lblSetCongSuatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 40, 20));

        lblDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDatCoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDatCoc.setForeground(new java.awt.Color(153, 153, 153));
        lblDatCoc.setText("Đặt Cọc");
        sdoGiaoCa.add(lblDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        lblTongChi.setBackground(new java.awt.Color(255, 255, 255));
        lblTongChi.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTongChi.setForeground(new java.awt.Color(153, 153, 153));
        lblTongChi.setText("Tổng Chi");
        sdoGiaoCa.add(lblTongChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        lblHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblHoaDon.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(153, 153, 153));
        lblHoaDon.setText("Hóa Đơn");
        sdoGiaoCa.add(lblHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        lblCaTruoc.setBackground(new java.awt.Color(255, 255, 255));
        lblCaTruoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblCaTruoc.setForeground(new java.awt.Color(153, 153, 153));
        lblCaTruoc.setText("Ca Trước");
        sdoGiaoCa.add(lblCaTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblNgay.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblNgay.setText("Ngày");
        sdoGiaoCa.add(lblNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 40, 20));
        sdoGiaoCa.add(spt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 620, 10));
        sdoGiaoCa.add(spt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 620, 10));

        lblTienPhatSinh.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhatSinh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTienPhatSinh.setForeground(new java.awt.Color(62, 73, 95));
        lblTienPhatSinh.setText("Tiền Phát Sinh");
        sdoGiaoCa.add(lblTienPhatSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 30));

        lblDaThu.setBackground(new java.awt.Color(255, 255, 255));
        lblDaThu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDaThu.setForeground(new java.awt.Color(62, 73, 95));
        lblDaThu.setText("Đã Thu");
        sdoGiaoCa.add(lblDaThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, 30));

        lblTongCong.setBackground(new java.awt.Color(255, 255, 255));
        lblTongCong.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTongCong.setForeground(new java.awt.Color(153, 153, 153));
        lblTongCong.setText("Tổng Cộng");
        sdoGiaoCa.add(lblTongCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        lblCongSuatPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblCongSuatPhong.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblCongSuatPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblCongSuatPhong.setText("Công Suất Phòng");
        sdoGiaoCa.add(lblCongSuatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 130, -1));

        lblCaTruc.setBackground(new java.awt.Color(255, 255, 255));
        lblCaTruc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblCaTruc.setForeground(new java.awt.Color(153, 153, 153));
        lblCaTruc.setText("Ca Trực");
        sdoGiaoCa.add(lblCaTruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, -1));

        lblCoKhach.setBackground(new java.awt.Color(255, 255, 255));
        lblCoKhach.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblCoKhach.setForeground(new java.awt.Color(255, 102, 102));
        lblCoKhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sleep (4).png"))); // NOI18N
        lblCoKhach.setText("1 Có Khách");
        lblCoKhach.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCoKhach.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoGiaoCa.add(lblCoKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 60));

        lblThongTinGiaoCa.setBackground(new java.awt.Color(255, 255, 255));
        lblThongTinGiaoCa.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblThongTinGiaoCa.setForeground(new java.awt.Color(62, 73, 95));
        lblThongTinGiaoCa.setText("GIAO CA");
        sdoGiaoCa.add(lblThongTinGiaoCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 30));

        lblSetNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgay.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgay.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgay.setText("16/09/22 22:08");
        sdoGiaoCa.add(lblSetNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        lblSetCaTruc.setBackground(new java.awt.Color(255, 255, 255));
        lblSetCaTruc.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetCaTruc.setForeground(new java.awt.Color(62, 73, 95));
        lblSetCaTruc.setText("Ca Đêm");
        sdoGiaoCa.add(lblSetCaTruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 20));

        lblThongKePhong.setBackground(new java.awt.Color(255, 255, 255));
        lblThongKePhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThongKePhong.setForeground(new java.awt.Color(62, 73, 95));
        lblThongKePhong.setText("Thống Kê Phòng");
        sdoGiaoCa.add(lblThongKePhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 30));

        lblBanGiao.setBackground(new java.awt.Color(255, 255, 255));
        lblBanGiao.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblBanGiao.setForeground(new java.awt.Color(153, 153, 153));
        lblBanGiao.setText("Bàn Giao");
        sdoGiaoCa.add(lblBanGiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, -1, -1));

        lblDatTruoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDatTruoc.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblDatTruoc.setForeground(new java.awt.Color(102, 153, 255));
        lblDatTruoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sleep (5).png"))); // NOI18N
        lblDatTruoc.setText("0 Đặt Trước");
        lblDatTruoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDatTruoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoGiaoCa.add(lblDatTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 60));

        lblTraPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTraPhong.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblTraPhong.setForeground(new java.awt.Color(255, 153, 0));
        lblTraPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sleep (3).png"))); // NOI18N
        lblTraPhong.setText("4 Trả Phòng");
        lblTraPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTraPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoGiaoCa.add(lblTraPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 100, 60));

        lblSetDaThu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDaThu.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblSetDaThu.setForeground(new java.awt.Color(97, 177, 90));
        lblSetDaThu.setText("1,400,000");
        sdoGiaoCa.add(lblSetDaThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 40));

        lblSetTongCong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTongCong.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetTongCong.setForeground(new java.awt.Color(97, 177, 90));
        lblSetTongCong.setText("1,400,000");
        sdoGiaoCa.add(lblSetTongCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 80, 30));

        lblSetHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblSetHoaDon.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetHoaDon.setForeground(new java.awt.Color(255, 102, 102));
        lblSetHoaDon.setText("1,400,000");
        sdoGiaoCa.add(lblSetHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 80, 30));

        lblSetCaTruoc.setBackground(new java.awt.Color(255, 255, 255));
        lblSetCaTruoc.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetCaTruoc.setForeground(new java.awt.Color(255, 102, 102));
        lblSetCaTruoc.setText("1,400,000");
        sdoGiaoCa.add(lblSetCaTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 30));

        lblSetTongChi.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTongChi.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetTongChi.setForeground(new java.awt.Color(255, 102, 102));
        lblSetTongChi.setText("1,400,000");
        sdoGiaoCa.add(lblSetTongChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 30));

        lblSetDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDatCoc.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetDatCoc.setForeground(new java.awt.Color(255, 102, 102));
        lblSetDatCoc.setText("1,400,000");
        sdoGiaoCa.add(lblSetDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 80, 30));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        sdoGiaoCa.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 30, 30));

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(680, 90));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(680, 90));
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(255, 255, 255));
        lblThoat.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(33, 150, 243));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout (6).png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 80, 40));

        lblGiaoCa.setBackground(new java.awt.Color(255, 255, 255));
        lblGiaoCa.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGiaoCa.setForeground(new java.awt.Color(33, 150, 243));
        lblGiaoCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exchange (3).png"))); // NOI18N
        lblGiaoCa.setText("Giao Ca");
        lblGiaoCa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoChucNang.add(lblGiaoCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblThoatMouseClicked

    private void txtBanGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanGiaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanGiaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinGiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinGiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinGiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinGiaoCa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_ThongTinGiaoCa dialog = new GUI_dal_ThongTinGiaoCa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBanGiao;
    private javax.swing.JLabel lblCaTruc;
    private javax.swing.JLabel lblCaTruoc;
    private javax.swing.JLabel lblCoKhach;
    private javax.swing.JLabel lblCongSuatPhong;
    private javax.swing.JLabel lblDaThu;
    private javax.swing.JLabel lblDatCoc;
    private javax.swing.JLabel lblDatTruoc;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGiaoCa;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblSetCaTruc;
    private javax.swing.JLabel lblSetCaTruoc;
    private javax.swing.JLabel lblSetCongSuatPhong;
    private javax.swing.JLabel lblSetDaThu;
    private javax.swing.JLabel lblSetDatCoc;
    private javax.swing.JLabel lblSetHoaDon;
    private javax.swing.JLabel lblSetNgay;
    private javax.swing.JLabel lblSetTongChi;
    private javax.swing.JLabel lblSetTongCong;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblThongKePhong;
    private javax.swing.JLabel lblThongTinGiaoCa;
    private javax.swing.JLabel lblTienPhatSinh;
    private javax.swing.JLabel lblTongChi;
    private javax.swing.JLabel lblTongCong;
    private javax.swing.JLabel lblTraPhong;
    private HELPER.PanelShadow sdoChucNang;
    private HELPER.PanelShadow sdoGiaoCa;
    private javax.swing.JSeparator spt_1;
    private javax.swing.JSeparator spt_2;
    private javax.swing.JTextField txtBanGiao;
    // End of variables declaration//GEN-END:variables
}
