/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.GUI_pnl_ChiTietPhong;
import java.awt.GridLayout;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_GiaPhong extends javax.swing.JPanel {

    public static int index;

    /**
     * Creates new form GUI_pnlSoDoPhong
     */
    public GUI_pnl_GiaPhong() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        scrFormChinh = new javax.swing.JScrollPane();
        pnlFormChinh = new javax.swing.JPanel();
        sdoChucNang = new HELPER.PanelShadow();
        lblTimKiem = new javax.swing.JLabel();
        lblGioPhutVao = new javax.swing.JLabel();
        lblGioPhutRa = new javax.swing.JLabel();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        dateDenNgay = new com.toedter.calendar.JDateChooser();
        lblDenNgay = new javax.swing.JLabel();
        lblTuNgay = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        lblSetTienPhong = new javax.swing.JLabel();
        lblSetDichVu = new javax.swing.JLabel();
        cboTang = new javax.swing.JComboBox<>();
        lblTienPhong1 = new javax.swing.JLabel();
        lblSetDatTruoc = new javax.swing.JLabel();
        lblTuNgay1 = new javax.swing.JLabel();
        lblTuNgay2 = new javax.swing.JLabel();
        cboTang1 = new javax.swing.JComboBox<>();
        lblTuNgay3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 730));
        setPreferredSize(new java.awt.Dimension(1150, 730));

        pnlFormChinh.setLayout(new java.awt.GridLayout(3, 4, 20, 20));
        scrFormChinh.setViewportView(pnlFormChinh);

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setForeground(new java.awt.Color(97, 177, 90));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(1150, 110));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(1150, 110));
        sdoChucNang.setShadowOpacity(0.4F);
        sdoChucNang.setShadowSize(9);
        sdoChucNang.setShadowType(HELPER.ShadowType.BOT);
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/magnifier (1).png"))); // NOI18N
        sdoChucNang.add(lblTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 30, 30));

        lblGioPhutVao.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutVao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutVao.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutVao.setText("00:00");
        lblGioPhutVao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(lblGioPhutVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 40, 20));

        lblGioPhutRa.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutRa.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutRa.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutRa.setText("00:00");
        lblGioPhutRa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(lblGioPhutRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 40, 20));

        dateTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateTuNgay.setForeground(new java.awt.Color(62, 73, 95));
        dateTuNgay.setDateFormatString("dd-MM-yyyy");
        sdoChucNang.add(dateTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, 20));

        dateDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateDenNgay.setForeground(new java.awt.Color(62, 73, 95));
        dateDenNgay.setDateFormatString("dd-MM-yyyy");
        sdoChucNang.add(dateDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 100, 20));

        lblDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblDenNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDenNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblDenNgay.setText("Đến Ngày");
        sdoChucNang.add(lblDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, 20));

        lblTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblTuNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTuNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblTuNgay.setText("Từ Ngày");
        sdoChucNang.add(lblTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, 20));

        lblTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTienPhong.setForeground(new java.awt.Color(33, 150, 243));
        lblTienPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money-back.png"))); // NOI18N
        lblTienPhong.setText("Tính Giá");
        lblTienPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTienPhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoChucNang.add(lblTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 70, 50));

        lblDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(153, 153, 153));
        lblDichVu.setText("Tổng Tiền");
        sdoChucNang.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, 20));

        lblSetTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTienPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetTienPhong.setForeground(new java.awt.Color(97, 177, 90));
        lblSetTienPhong.setText("3d 4h 5m");
        sdoChucNang.add(lblSetTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 80, 20));

        lblSetDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDichVu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetDichVu.setForeground(new java.awt.Color(97, 177, 90));
        lblSetDichVu.setText("1,200,000");
        sdoChucNang.add(lblSetDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 80, 20));

        cboTang.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboTang.setForeground(new java.awt.Color(62, 73, 95));
        cboTang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTang.setToolTipText("");
        cboTang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(cboTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 80, -1));

        lblTienPhong1.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTienPhong1.setForeground(new java.awt.Color(153, 153, 153));
        lblTienPhong1.setText("Thời Gian");
        sdoChucNang.add(lblTienPhong1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 20));

        lblSetDatTruoc.setBackground(new java.awt.Color(102, 153, 255));
        lblSetDatTruoc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetDatTruoc.setForeground(new java.awt.Color(255, 255, 255));
        lblSetDatTruoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetDatTruoc.setText("Tải Từ Excel");
        lblSetDatTruoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSetDatTruoc.setOpaque(true);
        sdoChucNang.add(lblSetDatTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, 40));

        lblTuNgay1.setBackground(new java.awt.Color(255, 255, 255));
        lblTuNgay1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTuNgay1.setForeground(new java.awt.Color(62, 73, 95));
        lblTuNgay1.setText("Kiểm Tra Giá");
        sdoChucNang.add(lblTuNgay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, 30));

        lblTuNgay2.setBackground(new java.awt.Color(255, 255, 255));
        lblTuNgay2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTuNgay2.setForeground(new java.awt.Color(153, 153, 153));
        lblTuNgay2.setText("Loại Giá");
        sdoChucNang.add(lblTuNgay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 30));

        cboTang1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboTang1.setForeground(new java.awt.Color(62, 73, 95));
        cboTang1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTang1.setToolTipText("");
        cboTang1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(cboTang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 80, -1));

        lblTuNgay3.setBackground(new java.awt.Color(255, 255, 255));
        lblTuNgay3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTuNgay3.setForeground(new java.awt.Color(153, 153, 153));
        lblTuNgay3.setText("Loại Phòng");
        sdoChucNang.add(lblTuNgay3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(scrFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTang;
    private javax.swing.JComboBox<String> cboTang1;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblGioPhutRa;
    private javax.swing.JLabel lblGioPhutVao;
    private javax.swing.JLabel lblSetDatTruoc;
    private javax.swing.JLabel lblSetDichVu;
    private javax.swing.JLabel lblSetTienPhong;
    private javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTienPhong1;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JLabel lblTuNgay1;
    private javax.swing.JLabel lblTuNgay2;
    private javax.swing.JLabel lblTuNgay3;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JScrollPane scrFormChinh;
    private HELPER.PanelShadow sdoChucNang;
    // End of variables declaration//GEN-END:variables
}
