/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author CherryCe
 */
public class GUI_frm_Menu extends javax.swing.JFrame {

    static boolean isShowHidden = false;

    /**
     * Creates new form GUI_frmMenu
     */
    public GUI_frm_Menu() {
        initComponents();
        setLocationRelativeTo(null);
        pnlFormChinh.add(new GUI_pnl_SoDoPhong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlToolBar = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        lblHidden = new javax.swing.JLabel();
        lblWiFi = new javax.swing.JLabel();
        lblSetTenMenu = new javax.swing.JLabel();
        pnlMenuBar = new javax.swing.JPanel();
        lblShowHiddenMenu = new javax.swing.JLabel();
        lblThuNgan = new javax.swing.JLabel();
        lblQuanLiKho = new javax.swing.JLabel();
        lblSoDoPhong = new javax.swing.JLabel();
        lblLichSuThuePhong = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        lblThietDatPhong = new javax.swing.JLabel();
        lblGiaoCa = new javax.swing.JLabel();
        lblQuanLiChiPhi = new javax.swing.JLabel();
        lblThietDatGiaPhong = new javax.swing.JLabel();
        lblThayDoiMatKhau = new javax.swing.JLabel();
        lblThongKeTrongNgay = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        lblQuanLiNguoiDung = new javax.swing.JLabel();
        pnlFormChinh = new javax.swing.JPanel();
        pnlKhoangTrang = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1360, 760));
        setUndecorated(true);

        pnlToolBar.setBackground(new java.awt.Color(62, 73, 95));
        pnlToolBar.setMinimumSize(new java.awt.Dimension(1360, 30));
        pnlToolBar.setPreferredSize(new java.awt.Dimension(1360, 30));
        pnlToolBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblExit.setBackground(new java.awt.Color(62, 73, 95));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        lblExit.setOpaque(true);
        lblExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblExitMouseMoved(evt);
            }
        });
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        pnlToolBar.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 30, 30));

        lblHidden.setBackground(new java.awt.Color(62, 73, 95));
        lblHidden.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHidden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/minus-sign.png"))); // NOI18N
        lblHidden.setOpaque(true);
        lblHidden.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHiddenMouseMoved(evt);
            }
        });
        lblHidden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHiddenMouseExited(evt);
            }
        });
        pnlToolBar.add(lblHidden, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 30, 30));

        lblWiFi.setBackground(new java.awt.Color(255, 255, 255));
        lblWiFi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWiFi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/wifi.png"))); // NOI18N
        pnlToolBar.add(lblWiFi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 30, 30));

        lblSetTenMenu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTenMenu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSetTenMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblSetTenMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetTenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hotel (1).png"))); // NOI18N
        lblSetTenMenu.setText("Game2K");
        pnlToolBar.add(lblSetTenMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        pnlMenuBar.setBackground(new java.awt.Color(62, 73, 95));
        pnlMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowHiddenMenu.setBackground(new java.awt.Color(62, 73, 95));
        lblShowHiddenMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowHiddenMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/more.png"))); // NOI18N
        lblShowHiddenMenu.setOpaque(true);
        lblShowHiddenMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblShowHiddenMenuMouseMoved(evt);
            }
        });
        lblShowHiddenMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowHiddenMenuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblShowHiddenMenuMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblShowHiddenMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 30, 30));

        lblThuNgan.setBackground(new java.awt.Color(62, 73, 95));
        lblThuNgan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThuNgan.setForeground(new java.awt.Color(255, 255, 255));
        lblThuNgan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money.png"))); // NOI18N
        lblThuNgan.setText("Thu Ngân");
        lblThuNgan.setOpaque(true);
        lblThuNgan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThuNganMouseMoved(evt);
            }
        });
        lblThuNgan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThuNganMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThuNganMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblThuNgan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 40));

        lblQuanLiKho.setBackground(new java.awt.Color(62, 73, 95));
        lblQuanLiKho.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblQuanLiKho.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLiKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/project-management.png"))); // NOI18N
        lblQuanLiKho.setText("Quản Lí Kho");
        lblQuanLiKho.setOpaque(true);
        lblQuanLiKho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLiKhoMouseMoved(evt);
            }
        });
        lblQuanLiKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLiKhoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLiKhoMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblQuanLiKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, 40));

        lblSoDoPhong.setBackground(new java.awt.Color(62, 73, 95));
        lblSoDoPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSoDoPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblSoDoPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/show-apps-button.png"))); // NOI18N
        lblSoDoPhong.setText("Sơ Đồ Phòng");
        lblSoDoPhong.setOpaque(true);
        lblSoDoPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSoDoPhongMouseMoved(evt);
            }
        });
        lblSoDoPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoDoPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoDoPhongMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblSoDoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 40));

        lblLichSuThuePhong.setBackground(new java.awt.Color(62, 73, 95));
        lblLichSuThuePhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLichSuThuePhong.setForeground(new java.awt.Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hotel.png"))); // NOI18N
        lblLichSuThuePhong.setText("Lịch Sử Thuê Phòng");
        lblLichSuThuePhong.setOpaque(true);
        lblLichSuThuePhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLichSuThuePhongMouseMoved(evt);
            }
        });
        lblLichSuThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLichSuThuePhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLichSuThuePhongMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblLichSuThuePhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 40));

        lblDichVu.setBackground(new java.awt.Color(62, 73, 95));
        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(255, 255, 255));
        lblDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/minibar (2).png"))); // NOI18N
        lblDichVu.setText("Minibar - Dịch Vụ");
        lblDichVu.setOpaque(true);
        lblDichVu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDichVuMouseMoved(evt);
            }
        });
        lblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDichVuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDichVuMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 40));

        lblThietDatPhong.setBackground(new java.awt.Color(62, 73, 95));
        lblThietDatPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThietDatPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblThietDatPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bed (1).png"))); // NOI18N
        lblThietDatPhong.setText("Thiết Đặt Phòng");
        lblThietDatPhong.setOpaque(true);
        lblThietDatPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThietDatPhongMouseMoved(evt);
            }
        });
        lblThietDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThietDatPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThietDatPhongMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblThietDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 190, 40));

        lblGiaoCa.setBackground(new java.awt.Color(62, 73, 95));
        lblGiaoCa.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGiaoCa.setForeground(new java.awt.Color(255, 255, 255));
        lblGiaoCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exchange (1).png"))); // NOI18N
        lblGiaoCa.setText("Giao Ca");
        lblGiaoCa.setOpaque(true);
        lblGiaoCa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblGiaoCaMouseMoved(evt);
            }
        });
        lblGiaoCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiaoCaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGiaoCaMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblGiaoCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 190, 40));

        lblQuanLiChiPhi.setBackground(new java.awt.Color(62, 73, 95));
        lblQuanLiChiPhi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblQuanLiChiPhi.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/assets (1).png"))); // NOI18N
        lblQuanLiChiPhi.setText("Quản Lí Chi Phí");
        lblQuanLiChiPhi.setOpaque(true);
        lblQuanLiChiPhi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLiChiPhiMouseMoved(evt);
            }
        });
        lblQuanLiChiPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLiChiPhiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLiChiPhiMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblQuanLiChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 190, 40));

        lblThietDatGiaPhong.setBackground(new java.awt.Color(62, 73, 95));
        lblThietDatGiaPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThietDatGiaPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/card.png"))); // NOI18N
        lblThietDatGiaPhong.setText("Thiết Đặt Giá Phòng");
        lblThietDatGiaPhong.setOpaque(true);
        lblThietDatGiaPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThietDatGiaPhongMouseMoved(evt);
            }
        });
        lblThietDatGiaPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThietDatGiaPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThietDatGiaPhongMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblThietDatGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 190, 40));

        lblThayDoiMatKhau.setBackground(new java.awt.Color(62, 73, 95));
        lblThayDoiMatKhau.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThayDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset-password (1).png"))); // NOI18N
        lblThayDoiMatKhau.setText("Thay Đổi Mật Khẩu");
        lblThayDoiMatKhau.setOpaque(true);
        lblThayDoiMatKhau.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThayDoiMatKhauMouseMoved(evt);
            }
        });
        lblThayDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThayDoiMatKhauMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThayDoiMatKhauMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblThayDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 190, 40));

        lblThongKeTrongNgay.setBackground(new java.awt.Color(62, 73, 95));
        lblThongKeTrongNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThongKeTrongNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/line-chart.png"))); // NOI18N
        lblThongKeTrongNgay.setText("Thống Kê Trong Ngày");
        lblThongKeTrongNgay.setOpaque(true);
        lblThongKeTrongNgay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongKeTrongNgayMouseMoved(evt);
            }
        });
        lblThongKeTrongNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeTrongNgayMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeTrongNgayMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblThongKeTrongNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 190, 40));

        lblDangXuat.setBackground(new java.awt.Color(62, 73, 95));
        lblDangXuat.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        lblDangXuat.setText("Đăng Xuất");
        lblDangXuat.setOpaque(true);
        lblDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseMoved(evt);
            }
        });
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 190, 40));

        lblQuanLiNguoiDung.setBackground(new java.awt.Color(62, 73, 95));
        lblQuanLiNguoiDung.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblQuanLiNguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profile-user (2).png"))); // NOI18N
        lblQuanLiNguoiDung.setText("Quản Lí Người Dùng");
        lblQuanLiNguoiDung.setOpaque(true);
        lblQuanLiNguoiDung.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLiNguoiDungMouseMoved(evt);
            }
        });
        lblQuanLiNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLiNguoiDungMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLiNguoiDungMouseExited(evt);
            }
        });
        pnlMenuBar.add(lblQuanLiNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 190, 40));

        pnlFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormChinh.setMinimumSize(new java.awt.Dimension(1150, 730));
        pnlFormChinh.setPreferredSize(new java.awt.Dimension(1150, 730));

        pnlKhoangTrang.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlKhoangTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlKhoangTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSoDoPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoDoPhongMouseClicked
        // TODO add your handling code here:      
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_SoDoPhong());
        lblSetTenMenu.setText("Game2K - " + lblSoDoPhong.getText());
        lblSoDoPhong.setForeground(new Color(33, 150, 243));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/app.png")));

        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblSoDoPhongMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblThuNganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuNganMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_ThuNgan());
        lblSetTenMenu.setText("Game2K - " + lblThuNgan.getText());
        lblThuNgan.setForeground(new Color(33, 150, 243));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money (1).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblThuNganMouseClicked

    private void lblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_DichVu());
        lblSetTenMenu.setText("Game2K - " + lblDichVu.getText());
        lblDichVu.setForeground(new Color(33, 150, 243));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (3).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblDichVuMouseClicked

    private void lblThietDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatPhongMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_ThietDatPhong());
        lblSetTenMenu.setText("Game2K - " + lblThietDatPhong.getText());
        lblThietDatPhong.setForeground(new Color(33, 150, 243));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (2).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblThietDatPhongMouseClicked

    private void lblGiaoCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaoCaMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_GiaoCa());
        lblSetTenMenu.setText("Game2K - " + lblGiaoCa.getText());
        lblGiaoCa.setForeground(new Color(33, 150, 243));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (4).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblGiaoCaMouseClicked

    private void lblThietDatGiaPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatGiaPhongMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_GiaPhong());
        lblSetTenMenu.setText("Game2K - " + lblThietDatGiaPhong.getText());
        lblThietDatGiaPhong.setForeground(new Color(33, 150, 243));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card (1).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblThietDatGiaPhongMouseClicked

    private void lblQuanLiNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiNguoiDungMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
//        pnlFormChinh.add(new GUI_pnl_());
        lblSetTenMenu.setText("Game2K - " + lblQuanLiNguoiDung.getText());
        lblQuanLiNguoiDung.setForeground(new Color(33, 150, 243));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (3).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblQuanLiNguoiDungMouseClicked

    private void lblSoDoPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoDoPhongMouseMoved
        // TODO add your handling code here:
        lblSoDoPhong.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblSoDoPhongMouseMoved

    private void lblSoDoPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoDoPhongMouseExited
        // TODO add your handling code here:
        lblSoDoPhong.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblSoDoPhongMouseExited

    private void lblThayDoiMatKhauMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThayDoiMatKhauMouseMoved
        // TODO add your handling code here:
        lblThayDoiMatKhau.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblThayDoiMatKhauMouseMoved

    private void lblThayDoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThayDoiMatKhauMouseExited
        // TODO add your handling code here:
        lblThayDoiMatKhau.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblThayDoiMatKhauMouseExited

    private void lblLichSuThuePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuThuePhongMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_ThuePhong());
        lblSetTenMenu.setText("Game2K - " + lblLichSuThuePhong.getText());
        lblLichSuThuePhong.setForeground(new Color(33, 150, 243));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel-sign (3).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblLichSuThuePhongMouseClicked

    private void lblThuNganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuNganMouseExited
        // TODO add your handling code here:
        lblThuNgan.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblThuNganMouseExited

    private void lblThuNganMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThuNganMouseMoved
        // TODO add your handling code here:
        lblThuNgan.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblThuNganMouseMoved

    private void lblLichSuThuePhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuThuePhongMouseExited
        // TODO add your handling code here:
        lblLichSuThuePhong.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblLichSuThuePhongMouseExited

    private void lblLichSuThuePhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLichSuThuePhongMouseMoved
        // TODO add your handling code here:
        lblLichSuThuePhong.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblLichSuThuePhongMouseMoved

    private void lblDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseExited
        // TODO add your handling code here:
        lblDichVu.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblDichVuMouseExited

    private void lblDichVuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseMoved
        // TODO add your handling code here:
        lblDichVu.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblDichVuMouseMoved

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        // TODO add your handling code here:
        lblDangXuat.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseMoved
        // TODO add your handling code here:
        lblDangXuat.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblDangXuatMouseMoved

    private void lblQuanLiNguoiDungMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiNguoiDungMouseMoved
        // TODO add your handling code here:
        lblQuanLiNguoiDung.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblQuanLiNguoiDungMouseMoved

    private void lblQuanLiNguoiDungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiNguoiDungMouseExited
        // TODO add your handling code here:
        lblQuanLiNguoiDung.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblQuanLiNguoiDungMouseExited

    private void lblQuanLiKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiKhoMouseExited
        // TODO add your handling code here:
        lblQuanLiKho.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblQuanLiKhoMouseExited

    private void lblQuanLiKhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiKhoMouseMoved
        // TODO add your handling code here:
        lblQuanLiKho.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblQuanLiKhoMouseMoved

    private void lblThongKeTrongNgayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeTrongNgayMouseExited
        // TODO add your handling code here:
        lblThongKeTrongNgay.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblThongKeTrongNgayMouseExited

    private void lblThongKeTrongNgayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeTrongNgayMouseMoved
        // TODO add your handling code here:
        lblThongKeTrongNgay.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblThongKeTrongNgayMouseMoved

    private void lblGiaoCaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaoCaMouseExited
        // TODO add your handling code here:
        lblGiaoCa.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblGiaoCaMouseExited

    private void lblGiaoCaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaoCaMouseMoved
        // TODO add your handling code here:
        lblGiaoCa.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblGiaoCaMouseMoved

    private void lblQuanLiChiPhiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiChiPhiMouseExited
        // TODO add your handling code here:
        lblQuanLiChiPhi.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblQuanLiChiPhiMouseExited

    private void lblQuanLiChiPhiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiChiPhiMouseMoved
        // TODO add your handling code here:
        lblQuanLiChiPhi.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblQuanLiChiPhiMouseMoved

    private void lblThietDatPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatPhongMouseExited
        // TODO add your handling code here:
        lblThietDatPhong.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblThietDatPhongMouseExited

    private void lblThietDatPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatPhongMouseMoved
        // TODO add your handling code here:
        lblThietDatPhong.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblThietDatPhongMouseMoved

    private void lblThietDatGiaPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatGiaPhongMouseExited
        // TODO add your handling code here:
        lblThietDatGiaPhong.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblThietDatGiaPhongMouseExited

    private void lblThietDatGiaPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThietDatGiaPhongMouseMoved
        // TODO add your handling code here:
        lblThietDatGiaPhong.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblThietDatGiaPhongMouseMoved

    private void lblShowHiddenMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenMenuMouseExited
        // TODO add your handling code here:
        lblShowHiddenMenu.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblShowHiddenMenuMouseExited

    private void lblShowHiddenMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenMenuMouseMoved
        // TODO add your handling code here:
        lblShowHiddenMenu.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblShowHiddenMenuMouseMoved

    private void lblHiddenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHiddenMouseExited
        // TODO add your handling code here:
        lblHidden.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblHiddenMouseExited

    private void lblHiddenMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHiddenMouseMoved
        // TODO add your handling code here:
        lblHidden.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblHiddenMouseMoved

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        lblExit.setBackground(new Color(62, 73, 95));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseMoved
        // TODO add your handling code here:
        lblExit.setBackground(new Color(78, 87, 103));
    }//GEN-LAST:event_lblExitMouseMoved

    private void lblThongKeTrongNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeTrongNgayMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
//        pnlFormChinh.add(new GUI_pnl_GiaoCa());
        lblSetTenMenu.setText("Game2K - " + lblThongKeTrongNgay.getText());
        lblThongKeTrongNgay.setForeground(new Color(33, 150, 243));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart (1).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblThongKeTrongNgayMouseClicked

    private void lblQuanLiKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiKhoMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_QuanLiKho());
        lblSetTenMenu.setText("Game2K - " + lblQuanLiKho.getText());
        lblQuanLiKho.setForeground(new Color(33, 150, 243));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management (1).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblQuanLiKhoMouseClicked

    private void lblQuanLiChiPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLiChiPhiMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
        pnlFormChinh.add(new GUI_pnl_QuanLiChiPhi());
        lblSetTenMenu.setText("Game2K - " + lblQuanLiChiPhi.getText());
        lblQuanLiChiPhi.setForeground(new Color(33, 150, 243));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (2).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblQuanLiChiPhiMouseClicked

    private void lblThayDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThayDoiMatKhauMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
//        pnlFormChinh.add(new GUI_pnl_GiaoCa());
        lblSetTenMenu.setText("Game2K - " + lblThayDoiMatKhau.getText());
        lblThayDoiMatKhau.setForeground(new Color(33, 150, 243));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (3).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
        lblDangXuat.setForeground(new Color(255, 255, 255));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout.png")));
    }//GEN-LAST:event_lblThayDoiMatKhauMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        pnlFormChinh.removeAll();
//        pnlFormChinh.add(new GUI_pnl_GiaoCa());
        lblDangXuat.setForeground(new Color(33, 150, 243));
        lblDangXuat.setIcon(new ImageIcon(getClass().getResource("/IMG/logout (7).png")));

        lblSoDoPhong.setForeground(new Color(255, 255, 255));
        lblSoDoPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/show-apps-button.png")));
        lblLichSuThuePhong.setForeground(new Color(255, 255, 255));
        lblLichSuThuePhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel.png")));
        lblDichVu.setForeground(new Color(255, 255, 255));
        lblDichVu.setIcon(new ImageIcon(getClass().getResource("/IMG/minibar (2).png")));
        lblThuNgan.setForeground(new Color(255, 255, 255));
        lblThuNgan.setIcon(new ImageIcon(getClass().getResource("/IMG/money.png")));
        lblGiaoCa.setForeground(new Color(255, 255, 255));
        lblGiaoCa.setIcon(new ImageIcon(getClass().getResource("/IMG/exchange (1).png")));
        lblQuanLiKho.setForeground(new Color(255, 255, 255));
        lblQuanLiKho.setIcon(new ImageIcon(getClass().getResource("/IMG/project-management.png")));
        lblQuanLiChiPhi.setForeground(new Color(255, 255, 255));
        lblQuanLiChiPhi.setIcon(new ImageIcon(getClass().getResource("/IMG/assets (1).png")));
        lblThietDatPhong.setForeground(new Color(255, 255, 255));
        lblThietDatPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/bed (1).png")));
        lblThietDatGiaPhong.setForeground(new Color(255, 255, 255));
        lblThietDatGiaPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/card.png")));
        lblQuanLiNguoiDung.setForeground(new Color(255, 255, 255));
        lblQuanLiNguoiDung.setIcon(new ImageIcon(getClass().getResource("/IMG/profile-user (2).png")));
        lblThayDoiMatKhau.setForeground(new Color(255, 255, 255));
        lblThayDoiMatKhau.setIcon(new ImageIcon(getClass().getResource("/IMG/reset-password (1).png")));
        lblThongKeTrongNgay.setForeground(new Color(255, 255, 255));
        lblThongKeTrongNgay.setIcon(new ImageIcon(getClass().getResource("/IMG/line-chart.png")));
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblShowHiddenMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenMenuMouseClicked
        // TODO add your handling code here:
        if (!isShowHidden) {
            lblSoDoPhong.setText(null);
            lblThuNgan.setText(null);
            lblLichSuThuePhong.setText(null);
            lblDichVu.setText(null);
            lblGiaoCa.setText(null);
            lblThongKeTrongNgay.setText(null);
            lblQuanLiKho.setText(null);
            lblQuanLiChiPhi.setText(null);
            lblThietDatPhong.setText(null);
            lblThietDatGiaPhong.setText(null);
            lblQuanLiNguoiDung.setText(null);
            lblThayDoiMatKhau.setText(null);
            lblDangXuat.setText(null);

            pnlMenuBar.setPreferredSize(new Dimension(40, 730));
            pnlFormChinh.setPreferredSize(new Dimension(1300, 730));

            isShowHidden = true;
        } else {
            lblSoDoPhong.setText("Sơ Đồ Phòng");
            lblThuNgan.setText("Thu Ngân");
            lblLichSuThuePhong.setText("Lịch Sử Thuê Phòng");
            lblDichVu.setText("Minibar - Dịch Vụ");
            lblGiaoCa.setText("Giao Ca");
            lblThongKeTrongNgay.setText("Thống Kê Trong Ngày");
            lblQuanLiKho.setText("Quản Lí Kho");
            lblQuanLiChiPhi.setText("Quản Lí Chi Phí");
            lblThietDatPhong.setText("Thiết Đặt Phòng");
            lblThietDatGiaPhong.setText("Thiết Đặt Giá Phòng");
            lblQuanLiNguoiDung.setText("Quản Lí Người Dùng");
            lblThayDoiMatKhau.setText("Thay Đổi Mật Khẩu");
            lblDangXuat.setText("Đăng Xuất");

            pnlMenuBar.setPreferredSize(new Dimension(200, 730));
            pnlFormChinh.setPreferredSize(new Dimension(1150, 730));
            GUI_pnl_SoDoPhong.sdoChuThich.setPreferredSize(new Dimension(1150, 110));

            isShowHidden = false;
        }
    }//GEN-LAST:event_lblShowHiddenMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGiaoCa;
    private javax.swing.JLabel lblHidden;
    private javax.swing.JLabel lblLichSuThuePhong;
    private javax.swing.JLabel lblQuanLiChiPhi;
    private javax.swing.JLabel lblQuanLiKho;
    private javax.swing.JLabel lblQuanLiNguoiDung;
    private javax.swing.JLabel lblSetTenMenu;
    private javax.swing.JLabel lblShowHiddenMenu;
    private javax.swing.JLabel lblSoDoPhong;
    private javax.swing.JLabel lblThayDoiMatKhau;
    private javax.swing.JLabel lblThietDatGiaPhong;
    private javax.swing.JLabel lblThietDatPhong;
    private javax.swing.JLabel lblThongKeTrongNgay;
    private javax.swing.JLabel lblThuNgan;
    private javax.swing.JLabel lblWiFi;
    private javax.swing.JPanel pnlFormChinh;
    private javax.swing.JPanel pnlKhoangTrang;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JPanel pnlToolBar;
    // End of variables declaration//GEN-END:variables

}
